### ISSUE TITLE
We should not be committing sensitive information

### ISSUE THREAD

**Issue by nik-markovic** [avnet-iotconnect/iotc-sphereos-sdk#3]
For example app_manifest.json contains ID Scope and device ID. These should be checked in as fillers and before you test, you can ensure that you do not accidentally commit those.

```git update-index --assume-unchanged path/to/file```

seup-project.sh could also be automatically flagging sensitive files like in the iotc-azurertos-sdk repo.

**Comment by alanlhc** [comment]
Already remove sensitive information from app_manifest.json and setup-project.sh.
