### ISSUE TITLE
Code review comments

### ISSUE THREAD

**Issue by nik-markovic** [avnet-iotconnect/iotc-sphereos-sdk#4]
Using this ticket to carry review comments. Not sure if anyone used "git blame" or any other mechanisms that may be better...

* Medium: Should we append our own copyright? I mean, we did take Microsoft's sample as a baseline, but we provided value at main.c.

* Minor: Is it \r\n or \n for Log_Debug? Inconsisency between main.c and azsphere_iothub_client.c for example.

* Minor: Would it be useful to anyone if we printed the exit code after the main loop at:

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/34797876ff7702df28898e73b315e88a1e0de8c3/samples/basic-sample/main.c#L325

I am not sure if EventLoop_Run will print any error message if it fails for whatevr reason.

* Minor:  typo: The app only support*s* DPS connection

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/34797876ff7702df28898e73b315e88a1e0de8c3/samples/basic-sample/main.c#L151

* Medium: Do we actually support IoTEgde connections with IoTConnect?:

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/34797876ff7702df28898e73b315e88a1e0de8c3/samples/basic-sample/main.c#L118

* Minor: iotedge_root_ca_path is not used:

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/samples/basic-sample/main.c#L73

* Medium: I don't think that res_str needs to be declared as static (also in other similar functions):

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/iotc-azsphere-sdk/azsphere-layer/src/azsphere_iothub_client.c#L101

* Minor: newValue should be named new_value: 

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/iotc-azsphere-sdk/azsphere-layer/src/azsphere_iothub_client.c#L159

* Medium: Why is device twin payload limited to 512 bytes? Is this sphere-specific or some limitation? Twin message size limit is 8k. If there is a limitation somewhere, we should state it in the comments.

https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/iotc-azsphere-sdk/azsphere-layer/src/azsphere_iothub_client.c#L244

* Medium: Should we either print the iothub_client_init return code on failure in iotconnect.c or print the reason for failing in iothub_client_init so that the user understands better why their connection failed:
https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/iotc-azsphere-sdk/azsphere-layer/src/azsphere_iothub_client.c#L367

* Meduim: same as above for iothub_client_connect
https://github.com/avnet-iotconnect/iotc-sphereos-sdk/blob/main/iotc-azsphere-sdk/azsphere-layer/src/azsphere_iothub_client.c#L390

* Minor: We should probably remove setup-project.sh, as we are now using git submodules.

**Comment by alanlhc** [comment]
Submitted a [pull request](https://github.com/avnet-iotconnect/iotc-sphereos-sdk/pull/5) to address all the issues here.
